name: Test

on:
  push: {branches: main}
  pull_request: {branches: main}

jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: "run tests"
      uses: Adzz/elixir_run_tests_action@v2.0.0
